export const CountryAPI = [
  { id: 1, title: "Georgia" },
  { id: 2, title: "Afghanistan" },
  { id: 3, title: "Albania" },
  { id: 4, title: "Algeria" },
  { id: 5, title: "Andorra" },
  { id: 6, title: "Angola" },
  { id: 7, title: "Argentina" },
  { id: 8, title: "Armenia" },
  { id: 9, title: "Australia" },
  { id: 10, title: "Austria" },
  { id: 11, title: "Azerbaijan" },
  { id: 12, title: "Bahamas" },
  { id: 13, title: "Bahrain" },
  { id: 14, title: "Bangladesh" },
  { id: 15, title: "Barbados" },
  { id: 16, title: "Belarus" },
  { id: 17, title: "Belgium" },
  { id: 18, title: "Belize" },
  { id: 19, title: "Benin" },
  { id: 20, title: "Bhutan" },
  { id: 21, title: "Bolivia" },
  { id: 22, title: "Bosnia and Herzegovina" },
  { id: 23, title: "Botswana" },
  { id: 24, title: "Brazil" },
  { id: 25, title: "Brunei" },
  { id: 26, title: "Bulgaria" },
  { id: 27, title: "Burkina Faso" },
  { id: 28, title: "Burundi" },
  { id: 29, title: "Cambodia" },
  { id: 30, title: "Cameroon" },
  { id: 31, title: "Canada" },
  { id: 32, title: "Cape Verde" },
  { id: 33, title: "Central African Republic" },
  { id: 34, title: "Chad" },
  { id: 35, title: "Chile" },
  { id: 36, title: "China" },
  { id: 37, title: "Colombia" },
  { id: 38, title: "Comoros" },
  { id: 39, title: "Congo" },
  { id: 40, title: "Costa Rica" },
  { id: 41, title: "Croatia" },
  { id: 42, title: "Cuba" },
  { id: 43, title: "Cyprus" },
  { id: 44, title: "Czech Republic" },
  { id: 45, title: "Denmark" },
  { id: 46, title: "Djibouti" },
  { id: 47, title: "Dominica" },
  { id: 48, title: "Dominican Republic" },
  { id: 49, title: "Ecuador" },
  { id: 50, title: "Egypt" },
  { id: 51, title: "El Salvador" },
  { id: 52, title: "Equatorial Guinea" },
  { id: 53, title: "Eritrea" },
  { id: 54, title: "Estonia" },
  { id: 55, title: "Eswatini" },
  { id: 56, title: "Ethiopia" },
  { id: 57, title: "Fiji" },
  { id: 58, title: "Finland" },
  { id: 59, title: "France" },
  { id: 60, title: "Gabon" },
  { id: 61, title: "Gambia" },
  { id: 62, title: "Germany" },
  { id: 63, title: "Ghana" },
  { id: 64, title: "Greece" },
  { id: 65, title: "Grenada" },
  { id: 66, title: "Guatemala" },
  { id: 67, title: "Guinea" },
  { id: 68, title: "Guyana" },
  { id: 69, title: "Haiti" },
  { id: 70, title: "Honduras" },
  { id: 71, title: "Hungary" },
  { id: 72, title: "Iceland" },
  { id: 73, title: "India" },
  { id: 74, title: "Indonesia" },
  { id: 75, title: "Iran" },
  { id: 76, title: "Iraq" },
  { id: 77, title: "Ireland" },
  { id: 78, title: "Israel" },
  { id: 79, title: "Italy" },
  { id: 80, title: "Jamaica" },
  { id: 81, title: "Japan" },
  { id: 82, title: "Jordan" },
  { id: 83, title: "Kazakhstan" },
  { id: 84, title: "Kenya" },
  { id: 85, title: "Kiribati" },
  { id: 86, title: "Kuwait" },
  { id: 87, title: "Kyrgyzstan" },
  { id: 88, title: "Laos" },
  { id: 89, title: "Latvia" },
  { id: 90, title: "Lebanon" },
  { id: 91, title: "Lesotho" },
  { id: 92, title: "Liberia" },
  { id: 93, title: "Libya" },
  { id: 94, title: "Liechtenstein" },
  { id: 95, title: "Lithuania" },
  { id: 96, title: "Luxembourg" },
  { id: 97, title: "Madagascar" },
  { id: 98, title: "Malawi" },
  { id: 99, title: "Malaysia" },
  { id: 100, title: "Maldives" },
];
