export const FlavorAPI = [
  { id: 1, title: "Vanilla", price: 0.75 },
  { id: 2, title: "Caramel", price: 0.8 },
  { id: 3, title: "Mocha", price: 1.0 },
  { id: 4, title: "Hazelnut", price: 0.9 },
  { id: 5, title: "French Vanilla", price: 1.0 },
  { id: 6, title: "Irish Cream", price: 1.1 },
  { id: 7, title: "Cinnamon", price: 0.6 },
  { id: 8, title: "Pumpkin Spice", price: 0.8 },
  { id: 9, title: "Toffee Nut", price: 0.95 },
  { id: 10, title: "Coconut", price: 0.85 },
  { id: 11, title: "Almond", price: 0.9 },
  { id: 12, title: "Butterscotch", price: 1.0 },
  { id: 13, title: "Chocolate", price: 1.1 },
  { id: 14, title: "Peppermint", price: 0.8 },
  { id: 15, title: "Maple", price: 0.85 },
  { id: 16, title: "Honey", price: 0.75 },
  { id: 17, title: "Chestnut Praline", price: 1.2 },
  { id: 18, title: "White Chocolate", price: 1.0 },
  { id: 19, title: "Raspberry", price: 1.1 },
  { id: 20, title: "Dark Chocolate", price: 1.15 },
];
